baseURL = "http://localhost/"
languageCode = "cs-cz"
title = "Oscloud News"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = false
  label.icon = "logo.png"
  label.text = "Oscloud News"


[outputs]
  home = ["HTML", "RSS", "JSON"]
[[menu.main]]
  name = "Archiv"
  url = "/archives/"
  weight = 10

[[menu.main]]
  name = "Vyhledávání"
  url = "/search/"
  weight = 20

[[menu.main]]
  name = "Tagy"
  url = "/tags/"
  weight = 30


