baseURL = "http://localhost/"
languageCode = "cs-cz"
title = "Oscloud News"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = false
  label.icon = "logo.png"
  label.text = "Oscloud News"


[outputs]
  home = ["HTML", "RSS", "JSON"]
[[menu.main]]
  name = "Archiv"
  url = "/archives/"
  weight = 10

[[menu.main]]
  name = "VyhledÃ¡vÃ¡nÃ­"
  url = "/search/"
  weight = 20

[[menu.main]]
  name = "Tagy"
  url = "/tags/"
  weight = 30

[[menu.main]]
  name = "ðŸ‡¨ðŸ‡¿"
  url = "/"
  weight = 1

[[params.socialIcons]]
  name = "mastodon"
  url = "https://mamutovo.cz/@oscloud"
  title = "Mastodon"

[[params.socialIcons]]
  name = "email"
  url = "mailto:info@oscloud.cz"
  title = "E-mail"

[[params.socialIcons]]
  name = "github"
  url = "https://git.arch-linux.cz/Oscloud"
  title = "Gitea (Oscloud)"




