baseURL = "https://blog.oscloud.cz"
languageCode = "cs-cz"
title = "Oscloud News"
theme = "PaperMod"
[pagination]
 pagerSize = 5

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.label]
  text = "Oscloud News"
  icon = "logo.png"
  iconHeight = 32

[params.homeInfoParams]
  Title = "Oscloud News"
  Content = """
Novinky, zmƒõny a d≈Øle≈æit√© informace kolem **[Oscloudu](https://oscloud.cz)**.

- aktualizace slu≈æeb  
- nov√© aplikace  
- provozn√≠ informace
"""

[[params.socialIcons]]
  name = "mastodon"
  url = "https://mamutovo.cz/@oscloud"

[[params.socialIcons]]
  name = "email"
  url = "mailto:info@oscloud.cz"

[[params.socialIcons]]
  name = "github"
  url = "https://git.arch-linux.cz/Oscloud"

[[params.socialIcons]]
  name = "rss"
  url = "/index.xml"

[[params.socialIcons]]
  name = "peertube"
  url = "https://vhsky.cz/c/oscloud/videos"

[[menu.main]]
  name = "üá®üáø"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Archiv"
  url = "/archives/"
  weight = 10

[[menu.main]]
  name = "Vyhled√°v√°n√≠"
  url = "/search/"
  weight = 20

[[menu.main]]
  name = "Tagy"
  url = "/tags/"
  weight = 30

[markup.goldmark.renderer]
  unsafe = true

